apiVersion: v1
kind: PersistentVolume
metadata:
  name: outline-server
  namespace: outline
spec:
  capacity:
    storage: "200Mi"
  volumeMode: Filesystem
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  local:
    path: /opt/outline/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3s-lt.slimjim.ru
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: outline-server-pvc
  namespace: outline
spec:
  storageClassName: "local-storage"
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "200Mi"